services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - service_network
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - service_network
    volumes:
      - ./backend:/backend
      - backend_node_modules:/backend/node_modules

  db:
    container_name: db
    image: postgres:15
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    # Environment variables to create default database with given credentials
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=urb_db
    networks:
      - service_network
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    name: URB_db_data
  frontend_node_modules:
    name: URB_frontend_node_modules
  backend_node_modules:
    name: URB_backend_node_modules

networks:
  service_network:
    driver: bridge
